#!/usr/bin/env python
#-*- coding: UTF-8 -*-

import underworlds
from underworlds.helpers import transformations
from underworlds.types import ENTITY, Node
from underworlds.tools.loader import ModelLoader

import logging; logger = logging.getLogger("underworlds.3d_face_loader")
logging.basicConfig(level=logging.DEBUG)


if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser(description="Underworlds 3D face loader")
    parser.add_argument("--prefix", default="face", help="Prefix of the node name used to identify a face.")
    parser.add_argument("world", help="Underworlds world to process")
    args = parser.parse_args()


    with underworlds.Context("3D face loader") as ctx:

        meshes = ModelLoader(args.world).load_meshes("../share/face.blend", ctx=ctx)
        face_mesh = meshes["face"]


        scene = ctx.worlds[args.world].scene

        updated_nodes = []

        for node in scene.nodes:
            if node.name.startswith(args.prefix):
                logger.info("Setting a 3D face mesh on node " + str(node))
                node.cad = list(face_mesh)
                node.hires = list(face_mesh)
                updated_nodes.append(node)

        for node in updated_nodes:
            scene.nodes.update(node)





